let testHelpers = {
  testHouse: {
    appliances: 'Tiger House',
    interiorFeatures: 'Integrated Weapons,Shark Tank,Harbor,Helipad,Booby-traps',
    construction: 'Modern',
    roof: 'Flat',
    exterior: 'Stucco',
    flooring: 'Laminate',
    homeId: 1,
    homeAddress: '345 Dood St.',
    price: 933946,
    beds: 5,
    baths: 1,
    rooms: 8,
    stories: 1,
    floorSize: 774,
    spaces: 'N/A',
    houseDescription:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut vitae eros massa. Etiam pretium ex purus, vel tempus diam pretium eget. Curabitur hendrerit, tortor sed ultrices finibus, tortor eros condimentum tortor, ac mollis augue arcu sed felis. Vestibulum et aliquet ex. Aenean cursus elementum eleifend. Curabitur sit amet finibus mauris, et porttitor justo. Maecenas imperdiet euismod elit, eu dictum nibh faucibus quis. Pellentesque quis ullamcorper dolor. Morbi vestibulum eget ligula non venenatis.',
    houseType: 'Villa',
    yearBuilt: 1954,
    heating: 'Nuclear Fission',
    cooling: 'Central',
    parking: 1,
    lotSize: 6429,
    daysListed: 1,
    saves: 1000
  },
  updateHouse: {
    appliances: 'Lions Den',
    interiorFeatures: 'Integrated Weapons,Shark Tank,Harbor,Helipad,Booby-traps',
    construction: 'Shabby Chic',
    roof: 'Terracotta',
    exterior: 'Wood',
    flooring: 'Hardwood',
    homeId: 1,
    homeAddress: '345 Dood St.',
    price: 933946,
    beds: 5,
    baths: 1,
    rooms: 8,
    stories: 1,
    floorSize: 774,
    spaces: 'N/A',
    houseDescription:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut vitae eros massa. Etiam pretium ex purus, vel tempus diam pretium eget. Curabitur hendrerit, tortor sed ultrices finibus, tortor eros condimentum tortor, ac mollis augue arcu sed felis. Vestibulum et aliquet ex. Aenean cursus elementum eleifend. Curabitur sit amet finibus mauris, et porttitor justo. Maecenas imperdiet euismod elit, eu dictum nibh faucibus quis. Pellentesque quis ullamcorper dolor. Morbi vestibulum eget ligula non venenatis.',
    houseType: 'Villa',
    yearBuilt: 1954,
    heating: 'Nuclear Fission',
    cooling: 'Central',
    parking: 1,
    lotSize: 6429,
    daysListed: 1,
    saves: 1000
  },
  makeTableQuery: `CREATE TABLE IF NOT EXISTS homes (
    appliances TEXT,
    interiorFeatures TEXT,
    construction TEXT,
    roof TEXT,
    exterior TEXT,
    flooring TEXT,
    homeId INT PRIMARY KEY AUTO_INCREMENT,
    homeAddress TEXT,
    price INT,
    beds INT,
    baths INT,
    rooms INT,
    stories INT,
    floorSize INT,
    spaces TEXT,
    houseDescription TEXT,
    houseType TEXT,
    yearBuilt INT,
    heating TEXT,
    cooling TEXT,
    parking INT,
    lotSize INT,
    daysListed INT,
    saves INT)`
};

module.exports = testHelpers;
