const house = {
  appliances: [
    'Refrigerator',
  ],
  interiorFeatures: [
    'Fireplace',
  ],
  _id: 48,
  construction: 'Pueblo',
  roof: 'Tile',
  exterior: 'Brick',
  flooring: 'Tile',
  address: '46 Oakwood Dr. \n  Glen Burnie, MD 21060',
  price: 588575,
  beds: 1,
  baths: 2,
  rooms: 4,
  stories: 2,
  floorSize: 1504,
  spaces: 'Pool',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut vitae eros massa. Etiam pretium ex purus, vel tempus diam pretium eget. Curabitur hendrerit, tortor sed ultrices finibus, tortor eros condimentum tortor, ac mollis augue arcu sed felis. Vestibulum et aliquet ex. Aenean cursus elementum eleifend. Curabitur sit amet finibus mauris, et porttitor justo. Maecenas imperdiet euismod elit, eu dictum nibh faucibus quis. Pellentesque quis ullamcorper dolor. Morbi vestibulum eget ligula non venenatis.',
  type: 'Townhouse',
  year: 1949,
  heating: 'Other',
  cooling: 'Central',
  parking: 2,
  lotSize: 3341,
  daysListed: 115,
  saves: 131,
  __v: 0,
};
export default house;
